### PR TITLE
Bug Fix on Creating Borrower Page

### LINKED ISSUE #27: BadMethodCallException
When adding a new borrower, **badmethodcall** - Method Filament\Forms\Components\TextInput::relationship does not exist.

                    Forms\Components\TextInput::make('added_by')

                    ->prefixIcon('heroicon-o-user')

                    ->relationship('added_by', 'name')

                    ->preload()

                    ->searchable()

                    ->required(),

### PR DESCRIPTION
**Pull request by bereank**
Changing Added By Input in Creating Borrower form from TextInput to Select  Input since TextInput doest not support relationship, this will fix Resolves #27

### CODE REVIEW

**Comment by chandachewe10** [comment]
Thanks am sure this will work. Just some changes which I want to make, this functionality will allow the person adding the borrower to add another person as the one who added the borrower. 
For example if the loan officer and am adding a borrower when I reach 'Added by' I can easily choose you (assuming you are in the system) under the drop down as a person who added that borrower. Please share your thoughts on that probably I added that in the wrong place in the first place. What about this. In the resources I can add this: 
`Forms\Components\TextInput::make('added_by')
                    ->hidden(),
`

And the create Borrower page I can also include this:
 ` // added by 

$data['added_by'] = auth()->user()->id
       return $data; `

So that the person adding the borrower cannot manipulate the person who added the borrower.
Let me know your thoughts and if a PR can be made

**Comment by bereank** [comment]
I believe that will work, if the idea is to capture Creator of the resource, its better be added Create Borrow page as mention,
Can i include this on this PR? @chandachewe10

**Comment by chandachewe10** [comment]
@bereank yes sure will appreciate

**Comment by bereank** [comment]
@chandachewe10  I have updated on the PR, Review on this PR

**Comment by chandachewe10** [comment]
@bereank thanks

**Pull request merged**
